name: Install and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-build:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install
        run: npm install
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
